// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNVCoyoCzI_celu5ktTzql3Rx1svxg4iU',
    appId: '1:462804977946:web:ea1bd060a1aba3803ac4a3',
    messagingSenderId: '462804977946',
    projectId: 'prestamosapp-4f041',
    authDomain: 'prestamosapp-4f041.firebaseapp.com',
    storageBucket: 'prestamosapp-4f041.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMrIv0JwvtJ6uJAtMp8XvFMd5eFh5aZQ',
    appId: '1:462804977946:android:d8dddef3e93ffd3d3ac4a3',
    messagingSenderId: '462804977946',
    projectId: 'prestamosapp-4f041',
    storageBucket: 'prestamosapp-4f041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWK1mBjmzfhAMOr_QkcOJvrTfz3XPliWc',
    appId: '1:462804977946:ios:06e30a921d43d22b3ac4a3',
    messagingSenderId: '462804977946',
    projectId: 'prestamosapp-4f041',
    storageBucket: 'prestamosapp-4f041.appspot.com',
    iosBundleId: 'com.example.appPrestamos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWK1mBjmzfhAMOr_QkcOJvrTfz3XPliWc',
    appId: '1:462804977946:ios:06e30a921d43d22b3ac4a3',
    messagingSenderId: '462804977946',
    projectId: 'prestamosapp-4f041',
    storageBucket: 'prestamosapp-4f041.appspot.com',
    iosBundleId: 'com.example.appPrestamos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNVCoyoCzI_celu5ktTzql3Rx1svxg4iU',
    appId: '1:462804977946:web:d976b0f3f8e077b63ac4a3',
    messagingSenderId: '462804977946',
    projectId: 'prestamosapp-4f041',
    authDomain: 'prestamosapp-4f041.firebaseapp.com',
    storageBucket: 'prestamosapp-4f041.appspot.com',
  );
}
